######################################################################
# Automatically generated by qmake (2.00a) Wed Feb 8 16:00:48 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

macx {
    CONFIG -= app_bundle
    CONFIG += warn_on static console
}


# Input
SOURCES += main.cpp
LIBS += -laspell
