######################################################################
# Automatically generated by qmake (2.00a) Wed Feb 8 16:00:48 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
LIBS += -laspell
