# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/erasertool
# Target is a library:  

INSTALLS += target 
target.path = /plugins/ 

HEADERS += erasertool.h
SOURCES += erasertool.cpp

CONFIG += plugin warn_on 
TEMPLATE = lib 
TARGET = erasertool

FRAMEWORK_DIR = "../../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../tools_config.pri)

include(../../../../tupiglobal.pri)

