# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/filters
# Target is a subdirs project 

CONFIG += ordered warn_on 
TEMPLATE = subdirs 
