copy C:\libav\bin\avcodec-56.dll C:\devel\sources\libav\
copy C:\libav\bin\avdevice-55.dll C:\devel\sources\libav\
copy C:\libav\bin\avfilter-5.dll C:\devel\sources\libav\
copy C:\libav\bin\avformat-56.dll C:\devel\sources\libav\
copy C:\libav\bin\avresample-2.dll C:\devel\sources\libav\
copy C:\libav\bin\avutil-54.dll C:\devel\sources\libav\
copy C:\libav\bin\libmp3lame-0.dll C:\devel\sources\libav\
copy C:\libav\bin\libogg-0.dll C:\devel\sources\libav\
copy C:\libav\bin\libopus-0.dll C:\devel\sources\libav\
copy C:\libav\bin\libvo-aacenc-0.dll C:\devel\sources\libav\
copy C:\libav\bin\libvorbis-0.dll C:\devel\sources\libav\
copy C:\libav\bin\libvorbisenc-2.dll C:\devel\sources\libav\
copy C:\libav\bin\libvorbisfile-3.dll C:\devel\sources\libav\
copy C:\libav\bin\libx264-142.dll C:\devel\sources\libav\
copy C:\libav\bin\swscale-3.dll C:\devel\sources\libav\
