
all: build

confclean:
	cd configure.tests 
	cd configure.tests/ffmpeg && make clean && make distclean  
	cd configure.tests/sound && make clean && make distclean
	cd configure.tests/gif && make clean && make distclean
	cd configure.tests/ming && make clean && make distclean

install_plugins:
	cd src/plugins && make install

build:
	sh build.sh

configure:
	sh configure

translate:
	sh scripts/translate.sh
