# File generated by kdevelop qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

CONFIG += warn_on 
TEMPLATE = subdirs 
SUBDIRS += src
