# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/import
# Target is a subdirs project 

CONFIG += release warn_on 
TEMPLATE = subdirs 
