#!/bin/bash

export TUPI_HOME="/usr"
export TUPI_SHARE="/usr/share"
export TUPI_LIB="/usr/lib64/tupi"
export TUPI_PLUGIN="/usr/lib64/tupi/plugins"
export TUPI_BIN="/usr/bin"

export LD_LIBRARY_PATH="${TUPI_LIB}:${TUPI_PLUGIN}:$LD_LIBRARY_PATH"

exec ${TUPI_BIN}/tupi.bin $*