#!/bin/bash

export TUPI_HOME="/usr/local/tupi"
export TUPI_SHARE="/usr/local/tupi/share"
export TUPI_LIB="/usr/local/tupi/lib"
export TUPI_PLUGIN="/usr/local/tupi/lib/plugins"
export TUPI_INCLUDE="/usr/local/tupi/include"
export TUPI_BIN="/usr/local/tupi/bin"

export LD_LIBRARY_PATH="${TUPI_LIB}:${TUPI_PLUGIN}:$LD_LIBRARY_PATH"

exec ${TUPI_BIN}/tupi.bin $*