# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/tools/filltool
# Target is a library:  

INSTALLS += target 
target.path = /plugins/

HEADERS += filltool.h 
SOURCES += filltool.cpp

CONFIG += plugin warn_on
TEMPLATE = lib
TARGET = tupifilltool

FRAMEWORK_DIR = "../../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../tools_config.pri)

include(../../../../tupiglobal.pri)
