# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export
# Target is a subdirs project 

include(../../../tupiglobal.pri)

SUBDIRS += genericexportplugin \
           smilexportplugin 

contains(DEFINES, HAVE_FFMPEG) {
        SUBDIRS += ffmpegplugin
}

KDEV_QTVER = 4

CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
