# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default/images
# Target is a library:  

INSTALLS = images 

images.target = .
images.commands = cp *.png $(INSTALL_ROOT)/themes/default/images
images.path = /themes/default/images

CONFIG += release \
warn_on \
staticlib
TEMPLATE = subdirs
