######################################################################
# Automatically generated by qmake (2.00a) Fri Jan 20 09:45:31 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lgif

# Input
SOURCES += main.cpp
