######################################################################
# Automatically generated by qmake (2.00a) Tue Jan 2 12:58:43 2007
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

macx {
    CONFIG -= app_bundle
    CONFIG += warn_on static console
}

# Input
SOURCES += main.cpp

QT += opengl
