######################################################################
# Automatically generated by qmake (2.00a) Tue Jan 2 12:58:43 2007
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += opengl
