# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default
# Target is a subdirs project 

SUBDIRS += icons \
           cursors \
           images 
QT += qt3support
CONFIG += release \
warn_on
TEMPLATE = subdirs
