######################################################################
# Automatically generated by qmake (2.00a) Sat Jan 21 01:49:18 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lming

# Input
SOURCES += main.cpp
