# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/pen
# Target is a library:  

include(../components_config.pri)

CONFIG += static

TEMPLATE = lib 
HEADERS += ktpenwidget.h ktpenthicknesswidget.h
SOURCES += ktpenwidget.cpp ktpenthicknesswidget.cpp

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)

