# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/themes/default/cursors
# Target is a library:  

INSTALLS = cursors 

cursors.target = .
cursors.commands = cp *.png $(INSTALL_ROOT)/themes/default/cursors
cursors.path = /themes/default/cursors

CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
macx{
    TEMPLATE = subdirs
}
