# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/debug
# Target is a library:  

# KDEV_QTVER = 4 

HEADERS += ktdebugwidget.h \
           ktdebugterm.h
SOURCES += ktdebugwidget.cpp \
           ktdebugterm.cpp

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)

include(../components_config.pri)

CONFIG += static
TEMPLATE = lib
