# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/debug
# Target is a library:  

HEADERS += ktdebugwidget.h \
           ktdebugterm.h
SOURCES += ktdebugwidget.cpp \
           ktdebugterm.cpp

CONFIG += static warn_on
TEMPLATE = lib
TARGET = debug

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../components_config.pri)

