# File generated by kdevelop's qmake manager . 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/framework
# Target is a subdirs project 

SUBDIRS += tcore tgui tsound tplugins
CONFIG += release \
warn_on
TEMPLATE = subdirs

