# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/export
# Target is a library:  

INSTALLS += target
target.path = /lib/

HEADERS += tupexportwidget.h 
SOURCES += tupexportwidget.cpp

CONFIG += dll warn_on
TEMPLATE = lib
TARGET = export

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../components_config.pri)
