# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/export
# Target is a library:  

KDEV_QTVER = 4 
include(../components_config.pri)

CONFIG += static
TEMPLATE = lib 
HEADERS += ktexportwidget.h 
SOURCES += ktexportwidget.cpp

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)
