# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins
# Target is a subdirs project 

SUBDIRS += tools \
           export \
           filters \
           import

CONFIG += ordered warn_on 
TEMPLATE = subdirs 
