# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins
# Target is a subdirs project 

SUBDIRS += export \
           filters \
           import \
           tools 

CONFIG += release warn_on 
TEMPLATE = subdirs 
