# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/scenes
# Target is a library:  

HEADERS += ktsceneslist.h \
           ktsceneswidget.h 
SOURCES += ktsceneslist.cpp \
           ktsceneswidget.cpp 

CONFIG += static warn_on
TEMPLATE = lib
TARGET = scenes

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../components_config.pri)
