# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/components/pen
# Target is a library:  

HEADERS += ktwitter.h \  
           ktwitterwidget.h
SOURCES += ktwitter.cpp \
           ktwitterwidget.cpp

CONFIG += static warn_on
TEMPLATE = lib
TARGET = twitter

FRAMEWORK_DIR = "../../framework"
include($$FRAMEWORK_DIR/framework.pri)
include(../components_config.pri)

