copy C:\libav\bin\avcodec-55.dll C:\tupi\sources\libav\
copy C:\libav\bin\avdevice-54.dll C:\tupi\sources\libav\
copy C:\libav\bin\avfilter-4.dll C:\tupi\sources\libav\
copy C:\libav\bin\avformat-55.dll C:\tupi\sources\libav\
copy C:\libav\bin\avresample-1.dll C:\tupi\sources\libav\
copy C:\libav\bin\avutil-53.dll C:\tupi\sources\libav\
copy C:\libav\bin\libmp3lame-0.dll C:\tupi\sources\libav\
copy C:\libav\bin\libogg-0.dll C:\tupi\sources\libav\
copy C:\libav\bin\libopus-0.dll C:\tupi\sources\libav\
copy C:\libav\bin\librtmp.dll C:\tupi\sources\libav\
copy C:\libav\bin\libvo-aacenc-0.dll C:\tupi\sources\libav\
copy C:\libav\bin\libvorbis-0.dll C:\tupi\sources\libav\
copy C:\libav\bin\libvorbisenc-2.dll C:\tupi\sources\libav\
copy C:\libav\bin\libvorbisfile-3.dll C:\tupi\sources\libav\
copy C:\libav\bin\libx264-125.dll C:\tupi\sources\libav\
copy C:\libav\bin\SDL.dll C:\tupi\sources\libav\
copy C:\libav\bin\swscale-2.dll C:\tupi\sources\libav\
copy C:\libav\bin\zlib1.dll C:\tupi\sources\libav\
