#!/bin/bash

APPNAME="Tupi"
APPVER="0.1"

TUPI_CONFIG=tupiglobal.pri
CONFIG_STATUS=configure.status

EMAIL='krawek [at] toonka [dot] com'

MAKE=`which make`

if [ ! "$QTDIR" = "" ]
then
        if [ -x "$QTDIR/bin/qmake" ]
        then
        QMAKE="$QTDIR/bin/qmake"
        fi
else
    QMAKE=`which qmake`
fi

LOG_FILE=build.log

export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin

# Look & feel

GREEN='\033[1;32m'
RED='\033[9;31m'
YELLOW='\033[1;33m'
NULLC='\033[0;0m'

function qpinfo ()
{
    echo -e $GREEN '*' $NULLC $1
    echo $1 >> $LOG_FILE
}

function qpwarn ()
{
    echo -e $YELLOW '*' $NULLC $1
    echo $1 >> $LOG_FILE
}

function qperror ()
{
    echo -e $RED '*' $NULLC $1
    echo $1 >> $LOG_FILE
}

function qpelec ()
{
    echo -en "$YELLOW * $NULLC $1 "
}

function detectQtVersion()
{
    COUNT=0
    VERSION_STR=`$QMAKE -query QT_VERSION | grep -o "\\w"`
    for version in $VERSION_STR
    do
        VERSION[$COUNT]=$version
        COUNT=${COUNT+1}
    done

    if [ "${VERSION[0]}" == "U" ]
    then
        qperror "You're using Qt 3"
        VERSION[1]=0
    fi
    
    if [ "${VERSION[0]}" != "4" -a ${VERSION[1]} -lt 1 ]
    then
        qperror "Please install Qt >= 4.1 or set QTDIR to Qt4 installation path"
        exit -1
    else
        qpinfo "Using Qt: `$QMAKE -query QT_VERSION `"
    fi
}
