# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += themes \
           framework \
           libtupi \
           store \
           libbase \
           net \
           libui \
           components \
           shell \
           plugins

CONFIG += release warn_on
TEMPLATE = subdirs
