# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/framework/tplugins
# Target is a subdirs project 

SUBDIRS += tgstengine 
CONFIG += release warn_on 
TEMPLATE = subdirs 
QMAKE_STRIP = echo
