######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 25 11:52:00 2006
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += gui core xml

# Input
SOURCES += main.cpp
