# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/plugins/export/mingplugin
# Target is a library:  

QT += xml 
INSTALLS += target 
target.path = /plugins/ 
KDEV_QTVER = 4 
include(../export_config.pri)
CONFIG += plugin 
TEMPLATE = lib 
HEADERS += mingplugin.h 
SOURCES += mingplugin.cpp 
!include(../../../../tupiglobal.pri){
    error("Please run configure first")
}
